#ifndef UBLKDRV_UAPI_GENL_H
#define UBLKDRV_UAPI_GENL_H

enum {
	UBLKDRV_GENL_BDEV_CMD_UNSPEC = 0,
	UBLKDRV_GENL_BDEV_CMD_CREATE = 1,
	UBLKDRV_GENL_BDEV_CMD_DESTROY = 2,
	//
	UBLKDRV_GENL_BDEV_CMDS_QTY
};

enum {
	UBLKDRV_GENL_BDEV_ATTR_UNSPEC = 0,
	UBLKDRV_GENL_BDEV_ATTR_NAME_SUFFIX = 1,
	UBLKDRV_GENL_BDEV_ATTR_NODE = 2,
	UBLKDRV_GENL_BDEV_ATTR_CAPACITY_SECTORS = 3,
	UBLKDRV_GENL_BDEV_ATTR_READ_ONLY = 4,
	//
	UBLKDRV_GENL_BDEV_ATTRS_QTY
};

#define UBLKDRV_GENL_NAME "ublk"

#endif /* UBLKDRV_UAPI_GENL_H */
