#ifndef UBLKDRV_UAPI_MAPPING_H
#define UBLKDRV_UAPI_MAPPING_H

#define UBLKDRV_UIO_KERNEL_TO_USER_DIR_SUFFIX ":req"
#define UBLKDRV_UIO_USER_TO_KERNEL_DIR_SUFFIX ":rsp"

#define UBLKDRV_UIO_MEM_CMDB_NAME "cmdb"
#define UBLKDRV_UIO_MEM_CELLC_NAME "cellc"
#define UBLKDRV_UIO_MEM_CELLS_NAME "cells"

#endif /* UBLKDRV_UAPI_MAPPING_H */
