#ifndef UBLKDRV_MAPPING_H
#define UBLKDRV_MAPPING_H

enum {
    UBLKDRV_UIO_MEM_CMDB  = 0,
    UBLKDRV_UIO_MEM_CELLC = 1,
    UBLKDRV_UIO_MEM_CELLS = 2,

    UBLKDRV_UIO_MEM_IDS_QTY,
};

enum {
    UBLKDRV_UIO_DIR_KERNEL_TO_USER = 0,
    UBLKDRV_UIO_DIR_USER_TO_KERNEL = 1,
    UBLKDRV_UIO_DIRS_QTY
};

#endif /* UBLKDRV_MAPPING_H */
